export enum CART_ACTIONS {
  ADDED_CART_ITEM = 'ADDED_CART_ITEM',
  REMOVED_CART_ITEM = 'REMOVED_CART_ITEM',
  CLEANED_CART = 'CLEANED_CART',
  ESTABLISHED_INITIAL_STATE = 'ESTABLISHED_INITIAL_STATE'
}
