export { isArrayOfObjects, isArrayOfPrimitives, isArrayOfString, isValidArray } from './isArrayOf.utility'
export { isNumber, isValidNumber, isValidRangeNumber } from './isValidNumber.utility'
export { isValidObject } from './isValidObject.utility'
export { isString } from './isString.utility'
export { isAllNull } from './isAllNull.utility'

export { setUpperCase } from './setUpperCase.utility'
export { getLocalStorageItem, updateLocalStore } from './localStorage.utility'
export { CATEGORY_KEYS, CATEGORY_VALUES, isValidCategory } from './isValidCategory.utility'
export { applyDiscount } from './applyDiscount.utility'
export { generateRange } from './generateRange.utility'
export { sanatize } from './sanatize.utility'
